apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
spec:
  source:
    repoURL: https://github.com/SorenHolstHansen/argocd-playground
    path: old_setup
  project: default
  destination:
    namespace: app
    server: https://kubernetes.default.svc
