apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-ks
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/SorenHolstHansen/argocd-playground
    path: new_setup
